sudo: required

language: php
php:
  - '7.1'

notifications:
  email:
    recipients:
      - baptistezegre@gmail.com
    on_success: always # default: change (other : never)
    on_failure: always # default: always

env:
  global:
    - URI="https://travis-ci.org/JulSar/tft-stardog/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Stardog"
    - SOFTWARE_DESCRIBE="Stardog"
    - VERSION="3.4.0"
    #- SPARQLSCORE_DATABASE="134.158.74.247"
    #- SPARQLSCORE_DATABASE="127.0.0.1:5820" #local
    #- SPARQLSCORE_DATABASE="0.0.0.0:49160" #local
    - SPARQLSCORE_DATABASE="127.0.0.1:5820" #local
    #- SPARQLSCORE_DATABASE="134.158.74.247" #local

services:
  - docker

before_install:
  - docker pull bordercloud/tft-jena-fuseki
  - docker pull bordercloud/tft-virtuoso7-stable
  - docker build -t stardog .
  - chmod +x curl_script.sh


script:
# Deploy TFT
# Run RDF database in order to save tests and results
  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft_database -d bordercloud/tft-jena-fuseki
  -   docker run --privileged --name instance.stardog -p 127.0.0.1:5820:5820 -h stardog -t -d stardog
#  -   docker exec -t -d instance.stardog /data/stardog/initDB.sh
##  -   docker run --privileged --name instance.tft_database -d tft-jena-fuseki

## Run quick test
#  -   docker run --privileged --name instance.jena-fuseki -h tft-jena-fuseki -d bordercloud/tft-jena-fuseki
#  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft_database -d bordercloud/tft-jena-fuseki
  -   ./curl_script.sh
  -   git clone --recursive https://github.com/JulSar/TFT.git
  -   cd TFT
  -   composer install --dev  
  -   php ./tft-testsuite -a -t sesame -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -l admin -p admin
  -   php ./tft -t sesame -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt virtusoso -tq http://172.17.0.2/test/query -tu http://172.17.0.2/test/update -r ${URI} -o ./junit --softwareName="${NAME}"  --softwareDescribeTag=${VERSION}  --softwareDescribe="${TRAVIS_COMMIT}"
  # -   php ./tft-score -t stardog -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}


